steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: [ '-c', 'docker build -t gcr.io/$PROJECT_ID/google-map-fetcher -f Dockerfile --build-arg APIKEY=$$APIKEY .' ]
  secretEnv: ['APIKEY']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/google-map-fetcher']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', 'google-map-fetcher', '--image', 'gcr.io/$PROJECT_ID/google-map-fetcher:latest', '--region', 'asia-northeast1', '--platform', 'managed', '--allow-unauthenticated']
images:
- 'gcr.io/$PROJECT_ID/google-map-fetcher'
secrets:
- kmsKeyName: projects/date-250913/locations/global/keyRings/date/cryptoKeys/google-map-fetcher
  secretEnv:
    APIKEY: CiQAAozwLYQUYnf8X0oJVeLBR56Aa7vqidQMnTIXFyorgvNXJrwSUADOjLGgTlEIvYbxZYtvfBEZvFXdg/tuF9+FWE8GMtXK8zOH1W3U67nkK9hNYB/oXRc/rM+VK53bI+QFiagnCTwncZUY6mr9J9niwveLci5Y